apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-hello-route
  namespace: default

spec:
  parentRefs:
  - name: gateway-api
    kind: Gateway

  hostnames:
  - k8s.evandrolovato.site

  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /app2
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: nginx2
      port: 80
      weight: 1
